import fs from "node:fs/promises";
import path from "node:path";
import Handlebars from "handlebars";
import type { PipelineState } from "../pipeline/types.js";

const TEMPLATE = `<!DOCTYPE html>
<html lang="{{language}}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{campaignName}} - Preview</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #333; line-height: 1.6; }
    .container { max-width: 900px; margin: 0 auto; padding: 2rem; }
    header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 3rem 2rem; border-radius: 12px; margin-bottom: 2rem; }
    header h1 { font-size: 2rem; margin-bottom: 0.5rem; }
    header p { opacity: 0.9; font-size: 1.1rem; }
    .stats { display: flex; gap: 1rem; margin-top: 1.5rem; }
    .stat { background: rgba(255,255,255,0.2); padding: 0.5rem 1rem; border-radius: 8px; font-size: 0.9rem; }
    .asset-card { background: white; border-radius: 12px; padding: 2rem; margin-bottom: 1.5rem; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
    .asset-card h2 { font-size: 1.3rem; margin-bottom: 0.25rem; }
    .asset-meta { color: #888; font-size: 0.85rem; margin-bottom: 1rem; display: flex; gap: 1rem; }
    .asset-meta span { background: #f0f0f0; padding: 0.2rem 0.6rem; border-radius: 4px; }
    .asset-content { white-space: pre-wrap; font-size: 0.95rem; border-left: 3px solid #667eea; padding-left: 1rem; }
    .review-badge { display: inline-block; padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.8rem; font-weight: 600; }
    .score-high { background: #d4edda; color: #155724; }
    .score-mid { background: #fff3cd; color: #856404; }
    .score-low { background: #f8d7da; color: #721c24; }
    footer { text-align: center; color: #999; padding: 2rem; font-size: 0.85rem; }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>{{campaignName}}</h1>
      <p>{{summary}}</p>
      <div class="stats">
        <span class="stat">{{assetCount}} Assets</span>
        {{#if overallScore}}<span class="stat">Score: {{overallScore}}/10</span>{{/if}}
        <span class="stat">{{language}}</span>
      </div>
    </header>

    {{#each assets}}
    <div class="asset-card">
      <h2>{{this.title}}</h2>
      <div class="asset-meta">
        <span>{{this.type}}</span>
        <span>{{this.id}}</span>
        {{#if this.score}}<span class="review-badge {{this.scoreClass}}">Score: {{this.score}}/10</span>{{/if}}
      </div>
      <div class="asset-content">{{this.content}}</div>
    </div>
    {{/each}}

    <footer>
      Generated by Content Creator Pipeline &mdash; {{generatedAt}}
    </footer>
  </div>
</body>
</html>`;

export async function exportHtmlPreview(outputDir: string, state: PipelineState): Promise<void> {
  if (!state.plan || !state.assets) return;

  const template = Handlebars.compile(TEMPLATE);

  const reviewMap = new Map(
    state.review?.assetReviews.map((r) => [r.assetId, r]) ?? []
  );

  const html = template({
    campaignName: state.plan.campaignName,
    summary: state.plan.summary,
    language: state.language,
    assetCount: state.assets.length,
    overallScore: state.review?.overallScore,
    generatedAt: new Date().toLocaleString(),
    assets: state.assets.map((a) => {
      const rev = reviewMap.get(a.id);
      const score = rev?.score;
      return {
        ...a,
        score,
        scoreClass: score ? (score >= 8 ? "score-high" : score >= 6 ? "score-mid" : "score-low") : "",
      };
    }),
  });

  await fs.writeFile(path.join(outputDir, "preview", "index.html"), html, "utf-8");
}
